name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          
      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef --version 10.0.8
          
      - name: Run Migrations
        run: dotnet ef database update --connection "${{ secrets.SQL_CONNECTION_STRING }}"
        
      - name: Publish
        run: dotnet publish WorkoutTracker.csproj -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: workout-tracker-uros
          package: ./publish